add retry and error handling for failing arvbox services

diff --git a/tools/arvbox/bin/arvbox b/tools/arvbox/bin/arvbox
--- a/tools/arvbox/bin/arvbox
+++ b/tools/arvbox/bin/arvbox
@@ -182,6 +182,9 @@ run() {
             git clone https://github.com/curoverse/sso-devise-omniauth-provider.git "$SSO_ROOT"
         fi
 
+	(cd "$ARVADOS_ROOT" && git status || (echo "ERROR: $ARVADOS_ROOT is not a git repo" && exit 1))
+	(cd "$SSO_ROOT" && git status || (echo "ERROR: $SSO_ROOT is not a git repo" && exit 1))
+
         if test "$CONFIG" = test ; then
 
             mkdir -p $VAR_DATA/test
diff --git a/tools/arvbox/lib/arvbox/docker/service/ready/run-service b/tools/arvbox/lib/arvbox/docker/service/ready/run-service
--- a/tools/arvbox/lib/arvbox/docker/service/ready/run-service
+++ b/tools/arvbox/lib/arvbox/docker/service/ready/run-service
@@ -24,7 +24,18 @@ do
     if nc -z localhost ${services[$s]} ; then
       echo "$s is ready at $localip:${services[$s]}"
       touch /tmp/arvbox-ready/$s
+      rm -f /var/lib/arvados/service-${s}-retries
+      rm -f /var/lib/arvados/service-${s}-retries.lock
     else
+      status=$(sv -w 7 check ${s})
+      running=$(echo "${status}" | grep '^ok: run:' && echo "yes" || echo "no")
+      if [[ "${running}" = "no" ]] ; then
+	  echo "${s} status ${status}"
+	  echo
+	  echo "${s} failed repeatedly and is no longer running, check \"arvbox log ${s}\" for more information about the failure."
+	  echo "It is now safe to quit arvbox using ctrl-c"
+	  sleep 86400
+      fi
       waiting="$waiting $s"
     fi
   fi
@@ -93,5 +104,7 @@ echo "Your Arvados-in-a-box is ready!"
 echo "Workbench is running at http://$localip"
 
 rm -r /tmp/arvbox-ready
+rm -f /var/lib/arvados/service-*-retries
+rm -f /var/lib/arvados/service-*-retries.lock
 
 sv stop ready >/dev/null
